const assert=require('node:assert/strict');
const fs=require('node:fs');
const sessionApi=require('../shared/signal-session.js');
const remote=require('../shared/signal-decision-remote.js');
const pilot=require('../signal-life-preview/core.js');
(async()=>{
const {deriveSignalDecision}=await import('../../CoverageFit/server/signal-decision-core.mjs');
const storage={getItem(){return null},setItem(){},removeItem(){}};
const fresh=()=>sessionApi.create(pilot.FLOW,{storage,location:{pathname:'/signal-life-preview/',search:''}});
const evaluate=s=>deriveSignalDecision(remote.payload(pilot.FLOW,s)).public;
const answer=(s,code)=>{const d=evaluate(s);assert.equal(d.decision,'ASK_ONE_SIGNAL');return sessionApi.answerQuestion(s,pilot.FLOW,d.nextQuestion,code,{storage}).session;};
let s=fresh();assert.equal(evaluate(s).nextQuestionId,'life_coverage_status');
for(const code of ['employer_only','open_to_review','within_30'])s=answer(s,code);
assert.equal(s.answers.length,3);assert.equal(evaluate(s).decision,'OFFER_HUMAN');
const h=pilot.handoff(s,'human');assert.deepEqual(h.canonicalSignals,s.canonicalSignals);assert.deepEqual(h.answers,s.answers);
assert.equal(h.contactPermissionGranted,false);assert.equal(h.previewOnly,true);assert.throws(()=>pilot.handoff(s,'automatic'));
assert.equal(pilot.applicationMapping(h.canonicalSignals).existing_life_coverage,'work');
s=sessionApi.goBack(s,pilot.FLOW,{storage});assert.equal(s.canonicalSignals.decisionTiming,undefined);
s=sessionApi.goBack(s,pilot.FLOW,{storage});s=answer(s,'not_interested');assert.equal(evaluate(s).decision,'CONTINUE_LATER');
let weak=answer(answer(fresh(),'none'),'researching');assert.equal(evaluate(weak).decision,'OFFER_LEARN');
let existing=fresh();for(const c of ['yes_personal','open_to_review','within_30'])existing=answer(existing,c);
assert.equal(evaluate(existing).nextQuestionId,'life_protection_goal');existing=answer(existing,'mortgage');
assert.deepEqual(pilot.applicationMapping(existing.canonicalSignals),{existing_life_coverage:'personal',protection_priority:'home_mortgage'});
const page=fs.readFileSync(__dirname+'/../signal-life-preview/index.html','utf8');
assert.doesNotMatch(page,/<input|<form|signal-decision-local/);
const app=fs.readFileSync(__dirname+'/../signal-life-preview/application/index.html','utf8');
assert.doesNotMatch(app,/formspree|life-secure-submit|type="submit"|data-life-secure-submit/);
console.log('PASS Life adaptive routing, three-answer happy path, Back, learn/later, explicit-action handoff, retained evidence, mapped coverage/goal and non-submitting preview');
})().catch(e=>{console.error(e);process.exitCode=1;});
